id = "elle-zed"
name = "Elle Syntax Highlight"
version = "0.0.1"
schema_version = 1
authors = ["tnixc <tnixxc@gmail.com>"]
description = "Syntax Highlight for Elle"
repository = "https://github.com/algebnaly/xdr.zed.git"

[grammars.elle]
repository = "https://github.com/Tnixc/tree-sitter-elle"
rev = "4aa4a68131fcf4d9dca6747c51f382bff77c16ee"
